import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import Box from '@/components/Box'
import AboutMe from '@/components/AboutMe'
import ResumeTabs from '@/components/ResumeTabs'
import Profile from '@/components/Profile'
import Infomation from '@/components/Infomation'
import Skills from '@/components/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className="row">
            <div className="col-lg-4 d-flex flex-column justify-content-start gap-4 pb-4 pb-lg-0">
             <Profile/>
             <Skills/>
             <Infomation/>
            
            </div>
            <div className="col-lg-8 d-flex flex-column justify-content-start gap-4">
              <AboutMe/>
              <ResumeTabs/>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
